apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: demo-rust
  name: rust
  namespace: parca
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-rust
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demo-rust
    spec:
      containers:
      - image: parca-demo:rust
        name: rust
        resources:
          limits:
            cpu: '100m'
            memory: '256Mi'
