apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: demo-python
  name: python
  namespace: parca
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-python
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demo-python
    spec:
      containers:
      - image: parca-demo:python
        name: python
        resources:
          limits:
            cpu: '100m'
            memory: '256Mi'
