apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo-nodejs
  name: nodejs
  namespace: parca
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-nodejs
  template:
    metadata:
      labels:
        app: demo-nodejs
    spec:
      containers:
      - image: parca-demo:nodejs
        name: parca-demo
        resources:
          limits:
            cpu: '100m'
            memory: '256Mi'
