---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: demo-nextjs
  name: nextjs
  namespace: parca
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-nextjs
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demo-nextjs
    spec:
      containers:
      - image: parca-demo:nextjs
        name: parca-demo-nextjs
        resources:
          limits:
            cpu: '100m'
            memory: '256Mi'
        ports:
        - containerPort: 5000
          name: http
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: demo-nextjs
  name: nextjs
  namespace: parca
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5000
    targetPort: 5000
  selector:
    app.kubernetes.io/name: demo-nextjs
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nextjs
  namespace: parca
  labels:
    serviceMonitor: demo-nextjs
    prometheus: k8s
spec:
  selector:
    matchLabels:
      service: demo-nextjs
  namespaceSelector:
    matchNames:
    - parca
  endpoints:
  - port: http
    path: /api/metrics
