apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: demo-php
  name: php
  namespace: parca
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-php
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demo-php
    spec:
      containers:
      - image: parca-demo:php
        name: php
        resources:
          limits:
            cpu: '100m'
            memory: '256Mi'
